/**
 * ArchitectureView
 *
 * Renders the codebase dependency graph (from GET /architecture) as a
 * Mermaid diagram. Users open this from a button in the chat header.
 *
 * Notes:
 * - Mermaid is heavy (~300 KB), so we lazy-load it only when the modal opens.
 * - Rendering into raw HTML is safe because the mermaid text is generated by
 *   our own backend from string-templated file names — no user input flows in.
 *   Still, we use mermaid.render() which returns sanitized SVG.
 */
import React, { useEffect, useRef, useState } from 'react';
import { X, Loader2, Download, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { apiService } from '@/services/api';
import { useToast } from '@/hooks/use-toast';

interface Props {
  open: boolean;
  onClose: () => void;
}

interface GraphState {
  mermaid: string;
  stats?: {
    files_scanned: number;
    kept_nodes: number;
    kept_edges: number;
    external_deps: Array<{ name: string; count: number }>;
  };
}

// Cache the mermaid module across opens so it's only loaded once
let mermaidPromise: Promise<typeof import('mermaid').default> | null = null;

const loadMermaid = async () => {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then(m => {
      const mermaid = m.default;
      mermaid.initialize({
        startOnLoad: false,
        theme: 'dark',
        securityLevel: 'strict',
        flowchart: {
          curve: 'basis',
          padding: 12,
          nodeSpacing: 40,
          rankSpacing: 60,
        },
      });
      return mermaid;
    });
  }
  return mermaidPromise;
};

export const ArchitectureView: React.FC<Props> = ({ open, onClose }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [graph, setGraph] = useState<GraphState | null>(null);
  const [svg, setSvg] = useState<string>('');
  const [maxNodes, setMaxNodes] = useState(50);
  const containerRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  // Fetch when opening
  useEffect(() => {
    if (!open) return;

    let cancelled = false;
    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await apiService.getArchitecture(maxNodes);
        if (cancelled) return;
        setGraph({ mermaid: data.mermaid, stats: data.stats });
      } catch (e: any) {
        if (!cancelled) setError(e?.message || 'Failed to load architecture');
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, [open, maxNodes]);

  // Render Mermaid to SVG whenever the mermaid text changes
  useEffect(() => {
    if (!graph?.mermaid) {
      setSvg('');
      return;
    }
    let cancelled = false;
    const render = async () => {
      try {
        const mermaid = await loadMermaid();
        // Unique id per render so mermaid doesn't cache DOM
        const id = `arch-${Date.now()}`;
        const { svg } = await mermaid.render(id, graph.mermaid);
        if (!cancelled) setSvg(svg);
      } catch (e: any) {
        if (!cancelled) setError('Failed to render diagram: ' + (e?.message || 'unknown'));
      }
    };
    render();
    return () => {
      cancelled = true;
    };
  }, [graph]);

  const downloadSvg = () => {
    if (!svg) return;
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `architecture-${Date.now()}.svg`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded', description: 'architecture.svg saved' });
  };

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-label="Architecture diagram"
    >
      <div
        className="w-full max-w-6xl max-h-[90vh] bg-background-elevated border border-border rounded-lg shadow-lg flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border">
          <div>
            <h2 className="font-semibold">Codebase Architecture</h2>
            {graph?.stats && (
              <p className="text-xs text-muted-foreground mt-0.5">
                {graph.stats.kept_nodes} files · {graph.stats.kept_edges} internal imports · scanned {graph.stats.files_scanned} files
              </p>
            )}
          </div>
          <div className="flex items-center gap-1">
            <label className="text-xs text-muted-foreground mr-2">Max nodes:</label>
            <select
              value={maxNodes}
              onChange={e => setMaxNodes(Number(e.target.value))}
              className="text-xs bg-background border border-border rounded px-2 py-1"
              disabled={loading}
            >
              <option value={30}>30</option>
              <option value={50}>50</option>
              <option value={100}>100</option>
              <option value={200}>200</option>
            </select>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setMaxNodes(m => m)}
              disabled={loading}
              aria-label="Refresh"
              title="Refresh"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={downloadSvg}
              disabled={!svg}
              aria-label="Download SVG"
              title="Download SVG"
            >
              <Download className="w-4 h-4" />
            </Button>
            <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close">
              <X className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-auto p-4">
          {loading && (
            <div className="flex items-center justify-center py-12 text-muted-foreground">
              <Loader2 className="w-5 h-5 animate-spin mr-2" />
              Building dependency graph...
            </div>
          )}
          {error && (
            <div className="p-6 text-destructive text-sm">Error: {error}</div>
          )}
          {!loading && !error && svg && (
            <div
              ref={containerRef}
              className="mermaid-container flex justify-center [&_svg]:max-w-full [&_svg]:h-auto"
              dangerouslySetInnerHTML={{ __html: svg }}
            />
          )}
        </div>

        {/* Footer: external deps summary */}
        {graph?.stats?.external_deps && graph.stats.external_deps.length > 0 && (
          <div className="border-t border-border p-3">
            <p className="text-xs text-muted-foreground mb-1.5">Top external dependencies:</p>
            <div className="flex flex-wrap gap-1.5">
              {graph.stats.external_deps.slice(0, 12).map(d => (
                <span
                  key={d.name}
                  className="text-xs bg-background px-2 py-0.5 rounded border border-border font-mono"
                  title={`Imported ${d.count} time(s)`}
                >
                  {d.name}
                  <span className="text-muted-foreground ml-1">×{d.count}</span>
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
